_core:
  default_config_hash: hMryGZ72dYhcT4Nl47e3sngAa2Plucwxr4skUVAaaug
links:
  -
    path: /
    priority: '1.0'
    changefreq: daily
  -
    path: /blog
    priority: '0.5'
    changefreq: daily
  -
    path: /search
    priority: '0.5'
